version: '3.9'

services:
  frontend:
    build: './FE'
    container_name: 'react-app'
    ports:
      - "5173:5173"
    volumes:
      - ./FE:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    env_file:
      - ./FE/.env

  backend:
    build: './BE'
    container_name: 'express-app'
    ports:
      - "4000:4000"
    volumes:
      - ./BE:/usr/src/node
      - /usr/src/node/node_modules
    depends_on:
      - mongo
    env_file:
      - ./BE/.env
  
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: