# swagger/paths/products.yaml
paths:
  /api/product/add-product:
    post:
      summary: Add a new product
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        "201":
          description: Product added successfully
          content:
            application/json:
              example:
                success: true
                message: "Product added successfully!"
        "400":
          description: Missing required fields
          content:
            application/json:
              example:
                success: false
                message: "Missing required fields!"
        "500":
          description: Internal server error
          content:
            application/json:
              example:
                success: false
                message: "Internal server error"

  /api/product/list-product:
    get:
      summary: Get all products (admin-user)
      tags: [Products]
      responses:
        "200":
          description: Successfully fetched all products
          content:
            application/json:
              example:
                success: true
                products:
                  - _id: "64b7f6f7c2e4c2f4a2d9a123"
                    name: "T-Shirt"
                    description: "High quality cotton T-shirt"
                    price: 299000
                    category: "Clothing"
                    subCategory: "Men"
                    sizes: ["S", "M", "L"]
                    bestseller: true
                    image:
                      [
                        "https://res.cloudinary.com/demo/image/upload/sample.jpg",
                      ]
                    date: "2025-09-10T10:00:00Z"
        "500":
          description: Internal server error
          content:
            application/json:
              example:
                success: false
                message: "Internal server error"

  /api/product/remove-product:
    delete:
      summary: Remove a product by ID
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  example: "64b7f6f7c2e4c2f4a2d9a123"
      responses:
        "200":
          description: Product removed successfully
          content:
            application/json:
              example:
                success: true
                message: "Product removed successfully!"
        "404":
          description: Product not found
          content:
            application/json:
              example:
                success: false
                message: "Product not found!"
        "500":
          description: Internal server error
          content:
            application/json:
              example:
                success: false
                message: "Internal server error"

  /api/product/single-product:
    post:
      summary: Get a single product by ID
      tags: [Products]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required:
                - id
              properties:
                id:
                  type: string
                  example: "64b7f6f7c2e4c2f4a2d9a123"
      responses:
        "200":
          description: Successfully fetched product
          content:
            application/json:
              example:
                success: true
                product:
                  _id: "64b7f6f7c2e4c2f4a2d9a123"
                  name: "T-Shirt"
                  description: "High quality cotton T-shirt"
                  price: 299000
                  category: "Clothing"
                  subCategory: "Men"
                  sizes: ["S", "M", "L"]
                  bestseller: true
                  image:
                    ["https://res.cloudinary.com/demo/image/upload/sample.jpg"]
                  date: "2025-09-10T10:00:00Z"
        "404":
          description: Product not found
          content:
            application/json:
              example:
                success: false
                message: "Product not found!"
        "500":
          description: Internal server error
          content:
            application/json:
              example:
                success: false
                message: "Internal server error"

  /api/product/filter:
    get:
      summary: "Filter, sort, and paginate products"
      description: "Filter products by category and subCategory, sort by price, and paginate results."
      tags: [Products]
      parameters:
        - name: category
          in: query
          description: "List of categories"
          required: false
          schema:
            type: string
            example: Men
        - name: subCategory
          in: query
          description: "List of subcategories"
          required: false
          schema:
            type: string
            example: Topwear
        - name: sort
          in: query
          description: "Sort by price"
          required: false
          schema:
            type: string
            enum: [low-high, high-low]
            example: low-high
        - name: page
          in: query
          description: "Page number"
          required: false
          schema:
            type: integer
            default: 1
            example: 1
        - name: limit
          in: query
          description: "Items per page"
          required: false
          schema:
            type: integer
            default: 10
            example: 10
      responses:
        "200":
          description: "Result"
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  total:
                    type: integer
                    example: 57
                  currentPage:
                    type: integer
                    example: 2
                  totalPages:
                    type: integer
                    example: 6
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "500":
          description: "Internal server error"
          content:
            application/json:
              example:
                success: false
                message: "Internal server error"
